name: Build and Push to ACR

on:
  workflow_dispatch:

env:
  IMAGE_NAME: todoui
  ACR_NAME: ${{ secrets.ACR_NAME }}

jobs:
  build-and-push:
    runs-on: self-hosted
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Debug ACR_NAME
        run: echo "ACR_NAME is" ${{ secrets.ACR_NAME }}
      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:${{ github.sha }}
